# Generated by Django 4.0.5 on 2022-07-31 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustName', models.TextField(max_length=25)),
                ('Reg', models.TextField(max_length=25)),
                ('timeslot', models.TimeField(blank=True, choices=[(0, '09:00 - 09:30'), (1, '10:00 - 10:30'), (2, '11:00 - 11:30'), (3, '12:00 - 12:30'), (4, '13:00 - 13:30'), (5, '14:00 - 14:30'), (6, '15:00 - 15:30'), (7, '16:00 - 16:30'), (8, '17:00 - 17:30')])),
                ('date', models.DateField(help_text='DD-MM-YYYY')),
                ('type', models.TextField(max_length=25)),
                ('number', models.TextField(max_length=25)),
                ('email', models.TextField(max_length=25)),
                ('VehicleType', models.TextField(max_length=25)),
                ('CarMake', models.TextField(max_length=25)),
                ('EngineType', models.TextField(max_length=25)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookings.staff')),
            ],
            options={
                'unique_together': {('staff', 'date', 'timeslot')},
            },
        ),
    ]
