# Generated by Django 4.0.5 on 2022-08-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0003_alter_bookings_carmake_alter_bookings_enginetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='status',
            field=models.IntegerField(choices=[(0, 'Booked'), (1, ' In Progress'), (2, ' Scrapped '), (3, ' Fixed ')], default=0, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
