# Generated by Django 4.0.5 on 2022-08-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0004_bookings_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='status',
            field=models.IntegerField(choices=[(0, 'Booked'), (1, ' In Progress'), (2, ' Scrapped '), (3, ' Fixed ')], default=0, verbose_name='Status'),
        ),
    ]
