# Generated by Django 4.0.5 on 2022-06-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.TextField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.TextField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.TextField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
