# Generated by Django 4.0.5 on 2022-06-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_products_brand_products_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
