# Generated by Django 4.0.5 on 2022-06-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_products_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=25)),
                ('products', models.ManyToManyField(to='Products.products')),
            ],
        ),
    ]
