# Generated by Django 4.0.5 on 2022-06-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_rename_products_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=25)),
                ('products', models.ManyToManyField(to='Products.product')),
            ],
        ),
    ]
