# Generated by Django 4.0.5 on 2022-06-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='products',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ManyToManyField(to='Products.category'),
        ),
    ]
