# Generated by Django 4.0.5 on 2022-06-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_remove_subcategory_products_subcategory_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
